### PR TITLE
Dependencies update

### PR DESCRIPTION
**Pull request by gaumut**

### CODE REVIEW

**Comment by YuhanLiin** [comment]
You need to update the MSRV to 1.64 to make the tests pass. Also need to fix lint failures. Otherwise everything looks good.

**Comment by gaumut** [comment]
There is still a lint about the size of LobpcgResult, I don’t know what to make of this.

**Comment by YuhanLiin** [comment]
That lint is an non-issue. Just add `#[allow(clippy::result_large_err)]` to make the lint go away. Also you need to update the MSRV in the CI jobs so they use a newer Rust version.

**Comment by YuhanLiin** [comment]
Can you update MSRV to 1.65 for proptest?

**Comment by YuhanLiin** [comment]
Thanks for the PR

**Pull request merged**
